export const SENSOR_GET_DATA = 'SENSOR_GET_DATA';
export const SENSOR_GET_DATA_SUCCESS = 'SENSOR_GET_DATA_SUCCESS';
export const SENSOR_GET_DATA_FALSE = "SENSOR_GET_DATA_FALSE";

export const SENSOR_CHANGE_DATA = 'SENSOR_CHANGE_DATA';
export const SENSOR_CHANGE_DATA_SUCCESS = 'SENSOR_CHANGE_DATA_SUCCESS';
export const SENSOR_CHANGE_DATA_FALSE = 'SENSOR_CHANGE_DATA_FALSE';

export const SEARCH_CHART_GET_DATA = 'SEARCH_CHART_GET_DATA';
export const SEARCH_CHART_GET_DATA_SUCCESS = 'SEARCH_CHART_GET_DATA_SUCCESS';
export const SEARCH_CHART_GET_DATA_FALSE = 'SEARCH_CHART_GET_DATA_FALSE';

export const CONNECT_API_ERROR = 'CONNECT_API_ERROR';