export const SENSOR_GET_DATA = 'SENSOR_GET_DATA';
export const SENSOR_GET_DATA_SUCCESS = 'SENSOR_GET_DATA_SUCCESS';

export const SENSOR_CHANGE_DATA = 'SENSOR_CHANGE_DATA';
export const SENSOR_CHANGE_DATA_SUCCESS = 'SENSOR_CHANGE_DATA_SUCCESS';

export const SENSOR_GET_CHART = 'SENSOR_GET_CHART';
export const SENSOR_API_FALSE = 'SENSOR_API_FALSE';

